name: set variables
description: set environment variables

runs:
 using: composite
 steps:
  - name: set dependency directory variables
    shell: bash
    run: |
     ROOT="$GITHUB_WORKSPACE"
     ANYKERNEL3="$ROOT/AnyKernel3"
     KERNEL_PATCHES="$ROOT/kernel_patches"
     echo "ROOT=$ROOT" >> $GITHUB_ENV
     echo "ANYKERNEL3=$ANYKERNEL3" >> $GITHUB_ENV
     echo "KERNEL_PATCHES=$KERNEL_PATCHES" >> $GITHUB_ENV
     
  - name: set common variable
    shell: bash
    run: |
     cd "$CONFIG"
     if [[ -d arch ]]; then
      COMMON="$(pwd)"
     elif [[ -d kernel_platform/common ]]; then
      COMMON="$(pwd)/kernel_platform/common"
     elif [[ -d kernel-6.6 ]]; then
      COMMON="$(pwd)/kernel-6.6"
     elif [[ -d kernel-6.1 ]]; then
      COMMON="$(pwd)/kernel-6.1"
     elif [[ -d kernel-5.10 ]]; then
      COMMON="$(pwd)/kernel-5.10"
     elif [[ -d kernel ]]; then
      COMMON="$(pwd)/kernel"
     fi
     
     echo "COMMON=$COMMON" >> $GITHUB_ENV
     chmod +x "$COMMON/scripts/config"
     
  - name: set defconfig variable
    shell: bash
    run: |
     if [[ $BRANCH == SM-A546B* ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-a54xnaxx_defconfig"
     elif [[ $BRANCH == SM-A546E* ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-a54xnsxx_defconfig"
     elif [[ "$BRANCH" == "SM-M146B-Oneui7-ADYJ2" ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8535-m14xnsxx_defconfig"
     elif [[ "$BRANCH" == "SM-S908B-Oneui8-bitK" ]]; then
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e9925-b0sxxx_defconfig"
     elif [[ $BRANCH == SM-X610* ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-gts9fepwifixx_defconfig"
     elif [[ "$BRANCH" == "SM-A166B-Oneui7" ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8535-a16xxx_defconfig"
     elif [[ $BRANCH == SM-A356E* ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e8835-a35xjvxx_defconfig"
     elif [[ $BRANCH == SM-S711* ]]; then
      GKI_DEFCONFIG="$COMMON/arch/arm64/configs/s5e9925-r11sksx_defconfig"
     else
       GKI_DEFCONFIG="$COMMON/arch/arm64/configs/gki_defconfig"
     fi
     echo "GKI_DEFCONFIG=$GKI_DEFCONFIG" >> $GITHUB_ENV
