name: 'Download Samsung Kernels'
description: "initialize and download the samsung kernel"

runs:
 using: composite
 steps:
   - name: Clone Kernel Source
     shell: bash
     run: |
      git clone --depth 1 -b $BRANCH --single-branch https://github.com/toraddict/Samsung_Kernels-Samsung-Galaxy-S23-SM-S916B.git $CONFIG
