name: Kernel Config - Samsung

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      susfs:
        required: true
        type: string
      bbg:
        required: true
        type: string
      unicodefix:
        required: true
        type: string
      zeromount:
        required: true
        type: string
      nomount:
        required: true
        type: string
      ksun:
        required: true
        type: string
      droidspace:
        required: true
        type: string
      ntsync:
        required: true
        type: string
      bbrv3:
        required: true
        type: string
      cache:
        required: true
        type: string
      ipv6_nat:
        required: true
        type: string
      optimization:
        required: true
        type: string
      ttl:
        required: true
        type: string
      lto:
        required: true
        type: string

jobs:
  build-kernels-a12:
    name: "Samsung-${{ matrix.branch }}-${{ matrix.kernel_version }}-${{ matrix.android_version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: "SM-S916B-Oneui8.5"
            build_type: "Bazel"
          

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch: ${{ matrix.branch }}
      build_type: ${{ matrix.build_type }}
      susfs: ${{ inputs.susfs }}
      bbg: ${{ inputs.bbg }}
      unicodefix: ${{ inputs.unicodefix }}
      zeromount: ${{ inputs.zeromount }}
      nomount: ${{ inputs.nomount }}
      ksun: ${{ inputs.ksun }}
      droidspace: ${{ inputs.droidspace }}
      ntsync: ${{ inputs.ntsync }}
      bbrv3: ${{ inputs.bbrv3 }}
      cache: ${{ inputs.cache }}
      ipv6_nat: ${{ inputs.ipv6_nat }}
      optimization: ${{ inputs.optimization }}
      ttl: ${{ inputs.ttl }}
      lto: ${{ inputs.lto }}
